name: Slack Notification
on:
  push:
    branches:
      - master
      - staging
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Success Notification
        uses: voxmedia/github-action-slack-notify-build@v1
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: app-alerts
          status: SUCCESS
          color: good
      - name: Failure Notification
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: app-alerts
          status: FAILED
          color: danger